apiVersion: v1
kind: Service
metadata:
  name: csi-snapshot-validation
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.resources.gardener.cloud/from-all-webhook-targets-allowed-ports: '[{"protocol":"TCP","port":443}]'
    {{- if .Values.csiSnapshotValidationWebhook.topologyAwareRoutingEnabled }}
    service.kubernetes.io/topology-mode: "auto"
    {{- end }}
  labels:
    {{- if .Values.csiSnapshotValidationWebhook.topologyAwareRoutingEnabled }}
    endpoint-slice-hints.resources.gardener.cloud/consider: "true"
    {{- end }}
spec:
  selector:
    app: snapshot-validation
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
