---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: csi-snapshot-controller-vpa
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: openstack-csi-snapshot-controller
      minAllowed:
        memory: {{ .Values.csiSnapshotController.resources.requests.memory }}
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csi-snapshot-controller
  updatePolicy:
    updateMode: Auto
