images:
  csi-driver-manila: image-repository:image-tag
  csi-driver-nfs: image-repository:image-tag
  csi-liveness-probe: image-repository:image-tag
  csi-provisioner: image-repository:image-tag
  csi-snapshotter: image-repository:image-tag
  csi-resizer: image-repository:image-tag

timeout: 3m
userAgentHeaders: []

global:
  genericTokenKubeconfigSecretName: secret

openstack:
  caCert: ""
resources:
  driverController:
    requests:
      cpu: 20m
      memory: 50Mi
  driverNFSController:
    requests:
      cpu: 20m
      memory: 50Mi
  provisioner:
    requests:
      cpu: 11m
      memory: 38Mi
  snapshotter:
    requests:
      cpu: 11m
      memory: 36Mi
  resizer:
    requests:
      cpu: 11m
      memory: 32Mi
  livenessProbe:
    requests:
      cpu: 11m
      memory: 32Mi

vpa:
  resourcePolicy:
    driverController: {}
    driverNFSController: {}
    provisioner: {}
    snapshotter: {}
    resizer: {}
    livenessProbe: {}

# CSI Manila spec
csimanila:
  # Runtime configuration
  runtimeConfig:
    enabled: false
    jsonData: |-
      {
        "nfs": {
          "matchExportLocationAddress": "172.168.122.0/24"
        }
      }

  topologyAwarenessEnabled: true

  # You may set ID of the cluster where manila-csi is deployed. This value will be appended
  # to share metadata in newly provisioned shares as `manila.csi.openstack.org/cluster=<cluster ID>`.
  clusterID: ""

# if enabled add the flags --kube-api-qps=100 and --kube-api-burst=200 to the csi-driver-controller
# only supported for Kubernetes versions >= 1.32
# TODO @hebelsan remove highQpsMode can be removed when Gardener removes support for Kubernetes versions 1.31
highQpsMode: false
