{{- if .Values.kubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: gardener-extension-admission-openstack-kubeconfig
  namespace: "{{ .Release.Namespace }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  kubeconfig: {{ .Values.kubeconfig | b64enc }}
{{- end }}
