apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: nfs.manila.csi.openstack.org
spec:
  attachRequired: false
  podInfoOnMount: false
  fsGroupPolicy: {{ .Values.nfs.fsGroupPolicy }}
---
