apiVersion: v1
kind: Secret
metadata:
  name: manila-csi-plugin
  namespace: {{ .Release.Namespace }}
data:
  os-authURL: {{ required "openstack.authURL needs to be set" .Values.openstack.authURL | b64enc }}
{{- if .Values.openstack.caCert }}
  os-certAuthorityPath: {{ "/var/run/csi-manila/ca.crt" | b64enc }} 
  ca.crt: {{ .Values.openstack.caCert | b64enc }}
{{- end}}
{{- if .Values.openstack.tlsInsecure }}
  os-TLSInsecure: {{ .Values.openstack.tlsInsecure | toString | b64enc }}
{{- end}}
  os-region: {{ required "openstack.region needs to be set" .Values.openstack.region | b64enc }}
{{- if .Values.openstack.applicationCredentialID }}
  os-applicationCredentialID: {{ required "openstack.applicationCredentialID needs to be set" .Values.openstack.applicationCredentialID | b64enc }}
  os-applicationCredentialSecret: {{ required "openstack.applicationCredentialSecret needs to be set" .Values.openstack.applicationCredentialSecret | b64enc }}
{{- else }}{{ if .Values.openstack.applicationCredentialName }}
  os-applicationCredentialName: {{ required "openstack.applicationCredentialName needs to be set" .Values.openstack.applicationCredentialName | b64enc }}
  os-applicationCredentialSecret: {{ required "openstack.applicationCredentialSecret needs to be set" .Values.openstack.applicationCredentialSecret | b64enc }}
  os-domainName: {{ required "openstack.domainName needs to be set" .Values.openstack.domainName | b64enc }}
  os-projectName: {{ required "openstack.projectName needs to be set" .Values.openstack.projectName | b64enc }}
{{- else }}
  os-domainName: {{ required "openstack.domainName needs to be set" .Values.openstack.domainName | b64enc }}
  os-projectName: {{ required "openstack.projectName needs to be set" .Values.openstack.projectName | b64enc }}
  os-userName: {{ required "openstack.userName needs to be set" .Values.openstack.userName | b64enc }}
  os-password: {{ required "openstack.password needs to be set" .Values.openstack.password | b64enc }}
{{- end }}
{{- end }}