---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
  name: csi-manila-nfs
provisioner: nfs.manila.csi.openstack.org
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- if $.Values.csimanila.mountOptions }}
mountOptions:
{{ toYaml $.Values.csimanila.mountOptions | indent 2 }}
{{- end }}
parameters:
  type: default
  shareNetworkID: {{ $.Values.openstack.shareNetworkID }}
  {{- if $.Values.openstack.shareClient}}
  nfs-shareClient: {{ $.Values.openstack.shareClient }}
  {{- end }}
  csi.storage.k8s.io/provisioner-secret-name: manila-csi-plugin
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-publish-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-publish-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: manila-csi-plugin
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ $.Release.Namespace }}

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
  name: csi-manila-nfs-auto
provisioner: nfs.manila.csi.openstack.org
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- if $.Values.csimanila.mountOptions }}
mountOptions:
{{ toYaml $.Values.csimanila.mountOptions | indent 2 }}
{{- end }}
parameters:
  type: default
  autoTopology: "true"
  shareNetworkID: {{ $.Values.openstack.shareNetworkID }}
  {{- if $.Values.openstack.shareClient}}
  nfs-shareClient: {{ $.Values.openstack.shareClient }}
  {{- end }}
  csi.storage.k8s.io/provisioner-secret-name: manila-csi-plugin
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-publish-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-publish-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: manila-csi-plugin
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ $.Release.Namespace }}

{{- range .Values.openstack.availabilityZones }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
  name: csi-manila-nfs-{{ . }}
provisioner: nfs.manila.csi.openstack.org
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- if $.Values.csimanila.mountOptions }}
mountOptions:
{{ toYaml $.Values.csimanila.mountOptions | indent 2 }}
{{- end }}
parameters:
  type: default
  availability: {{ required "openstack.availabilityZones needs to be set" . }}
  shareNetworkID: {{ $.Values.openstack.shareNetworkID }}
  {{- if $.Values.openstack.shareClient}}
  nfs-shareClient: {{ $.Values.openstack.shareClient }}
  {{- end }}
  csi.storage.k8s.io/provisioner-secret-name: manila-csi-plugin
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-publish-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-publish-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: manila-csi-plugin
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ $.Release.Namespace }}
{{ end }}

{{- range .Values.openstack.availabilityZones }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
  name: csi-manila-nfs-constrain-{{ . }}
provisioner: nfs.manila.csi.openstack.org
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- if $.Values.csimanila.mountOptions }}
mountOptions:
{{ toYaml $.Values.csimanila.mountOptions | indent 2 }}
{{- end }}
allowedTopologies:
- matchLabelExpressions:
  - key: topology.manila.csi.openstack.org/zone
    values:
      - "{{ . }}"
parameters:
  type: default
  availability: {{ required "openstack.availabilityZones needs to be set" . }}
  shareNetworkID: {{ $.Values.openstack.shareNetworkID }}
  {{- if $.Values.openstack.shareClient}}
  nfs-shareClient: {{ $.Values.openstack.shareClient }}
  {{- end }}
  csi.storage.k8s.io/provisioner-secret-name: manila-csi-plugin
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-publish-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-publish-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: manila-csi-plugin
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ $.Release.Namespace }}
{{ end }}