---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
  name: csi-manila-nfs
provisioner: nfs.manila.csi.openstack.org
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: default
  shareNetworkID: {{ required "openstack.shareNetworkID needs to be set" $.Values.openstack.shareNetworkID }}
  nfs-shareClient: {{ required "openstack.shareClient needs to be set" $.Values.openstack.shareClient }}
  csi.storage.k8s.io/provisioner-secret-name: manila-csi-plugin
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-publish-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-publish-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: manila-csi-plugin
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ $.Release.Namespace }}

{{- range .Values.openstack.availabilityZones }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
  name: csi-manila-nfs-{{ . }}
provisioner: nfs.manila.csi.openstack.org
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: default
  availability: {{ required "openstack.availabilityZones needs to be set" . }}
  shareNetworkID: {{ required "openstack.shareNetworkID needs to be set" $.Values.openstack.shareNetworkID }}
  nfs-shareClient: {{ required "openstack.shareClient needs to be set" $.Values.openstack.shareClient }}
  csi.storage.k8s.io/provisioner-secret-name: manila-csi-plugin
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-publish-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-publish-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: manila-csi-plugin
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ $.Release.Namespace }}
{{ end }}

{{- range .Values.openstack.availabilityZones }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
  name: csi-manila-nfs-constrain-{{ . }}
provisioner: nfs.manila.csi.openstack.org
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.manila.csi.openstack.org/zone
    values:
      - "{{ . }}"
parameters:
  type: default
  availability: {{ required "openstack.availabilityZones needs to be set" . }}
  shareNetworkID: {{ required "openstack.shareNetworkID needs to be set" $.Values.openstack.shareNetworkID }}
  nfs-shareClient: {{ required "openstack.shareClient needs to be set" $.Values.openstack.shareClient }}
  csi.storage.k8s.io/provisioner-secret-name: manila-csi-plugin
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/node-publish-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-publish-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: manila-csi-plugin
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ $.Release.Namespace }}
{{ end }}