{{- if .Values.vpaEnabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: csi-driver-manila-node
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: driver-manila-nfs-node
      minAllowed:
        cpu: {{ .Values.resources.driverNode.requests.cpu }}
        memory: {{ .Values.resources.driverNode.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.vpa.resourcePolicy.driverNode.maxAllowed.cpu }}
        memory: {{ .Values.vpa.resourcePolicy.driverNode.maxAllowed.memory }}
      controlledValues: RequestsOnly
    - containerName: driver-nfs-nfs-node
      minAllowed:
        cpu: {{ .Values.resources.driverNode.requests.cpu }}
        memory: {{ .Values.resources.driverNode.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.vpa.resourcePolicy.driverNode.maxAllowed.cpu }}
        memory: {{ .Values.vpa.resourcePolicy.driverNode.maxAllowed.memory }}
      controlledValues: RequestsOnly
    - containerName: nfs-registrar
      minAllowed:
        cpu: {{ .Values.resources.nodeDriverRegistrar.requests.cpu }}
        memory: {{ .Values.resources.nodeDriverRegistrar.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.vpa.resourcePolicy.nodeDriverRegistrar.maxAllowed.cpu }}
        memory: {{ .Values.vpa.resourcePolicy.nodeDriverRegistrar.maxAllowed.memory }}
      controlledValues: RequestsOnly
    - containerName: nfs-liveness-probe
      minAllowed:
        cpu: {{ .Values.resources.livenessProbe.requests.cpu }}
        memory: {{ .Values.resources.livenessProbe.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.vpa.resourcePolicy.livenessProbe.maxAllowed.cpu }}
        memory: {{ .Values.vpa.resourcePolicy.livenessProbe.maxAllowed.memory }}
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: csi-driver-manila-node
  updatePolicy:
    updateMode: "Auto"
{{- end }}