{{- if .Values.vpaEnabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: csi-driver-manila-node
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: driver-manila-nfs-node
      controlledValues: RequestsOnly
    - containerName: driver-nfs-nfs-node
      controlledValues: RequestsOnly
    - containerName: nfs-registrar
      controlledValues: RequestsOnly
    - containerName: nfs-liveness-probe
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: csi-driver-manila-node
  updatePolicy:
    updateMode: "Auto"
{{- end }}