---
apiVersion: v1
kind: Secret
metadata:
  name: backupprovider
  namespace: garden
type: Opaque
data:
# authURL: base64(authentication-url)
# domainName: base64(domain-name)
# tenantName: base64(tenant-name)
### either use username/password
# username: base64(username)
# password: base64(password)
### or application credentials
# applicationCredentialID: base64(app-credential-id)
# applicationCredentialName: base64(app-credential-name) # optional
# applicationCredentialSecret: base64(app-credential-secret)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: BackupBucket
metadata:
  name: cloud--os--fg2d6
spec:
  type: openstack
  region: eu-west-1
  secretRef:
    name: backupprovider
    namespace: garden