apiVersion: v1
kind: Namespace
metadata:
  name: shoot--foobar--openstack
  labels:
    backup.gardener.cloud/provider: openstack
    seed.gardener.cloud/provider: openstack
    shoot.gardener.cloud/provider: openstack
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foobar--openstack
type: Opaque
data:
  domainName: ZG9tYWluLW9wZW4tc3RhY2s=
  tenantName: dGVuYW50LW9wZW4tc3RhY2s=
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--openstack
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: CloudProfile
    spec:
      providerConfig:
        apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
        kind: CloudProfileConfig
        keystoneURL: https://localhost
  seed:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Shoot
    spec:
      cloud:
        openstack:
          networks:
            pods: 10.250.0.0/19
      kubernetes:
        version: 1.13.4
      hibernation:
        enabled: false
    status:
      lastOperation:
        state: Succeeded
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: ControlPlane
metadata:
  name: control-plane
  namespace: shoot--foobar--openstack
spec:
  type: openstack
  region: europe-west1
  secretRef:
    name: cloudprovider
    namespace: shoot--foobar--openstack
  providerConfig:
    apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
    kind: ControlPlaneConfig
    loadBalancerProvider: provider
    cloudControllerManager:
      featureGates:
        CustomResourceValidation: true
  infrastructureProviderStatus:
    apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
    networks:
      floatingPool:
        id: vpc-1234
      subnets:
      - purpose: nodes
        id: subnetid
