apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gardener-extension-admission-openstack
webhooks:
- name: mutation.openstack.provider.extensions.gardener.cloud
  rules:
  - apiGroups:
    - "core.gardener.cloud"
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shoots
  failurePolicy: Fail
  # Please make sure you are running `gardener@v1.42` or later before enabling this object selector.
  objectSelector:
    matchLabels:
      provider.extensions.gardener.cloud/openstack: "true"
  namespaceSelector: {}
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://localhost:9443/webhooks/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrekNDQWVPZ0F3SUJBZ0lSQUkxdHdSZGtOQnlLSnBzdkcwT0tOUGt3RFFZSktvWklodmNOQVFFTEJRQXcKRnpFVk1CTUdBMVVFQXhNTVoyRnlaR1Z1WlhJdFpHVjJNQjRYRFRJeE1ERXlNVEV3TXpJeE5sb1hEVE14TURFeQpNVEV3TXpJeE5sb3dGekVWTUJNR0ExVUVBeE1NWjJGeVpHVnVaWEl0WkdWMk1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXNaZ2JqOXFXTE8zZnNHRUFWVkdKNi9iQ0dpdmZwa2FqUGhuWWdUODkKa3BPOTNkemFoOFdiYUUvYWFYRzY5MWJuMnpmb1pPUG9RdmNjL25QMWxrWUdYcGhUR21yN24yeTRQUHhDSVRqVgp5WC9BN2gvb1ZPVEFHWnhoUW14UTdrUDBwSStheTJpa2tVdW1WTjVnWVJkQ1hKMEI4TEhHYXBJTDBOcXI2M1paCm9LRUNWa3Z0ODNwdW9ybG5TL3Z2OU1adzZ6YmFDNjBWbC91NXM1anRRNDlUUXYvdUdGOUNxZmUrckVCZ3hrMzEKeTRXazNuMVVJUkxWLzFOY1hXTzh3T3JRWXp3TS9jbXFlV0w4a253SFh1ZzFVRDE3T2x1SS80TDF0b3M0dG5IYQo5V2tJcXlTRnYxS3lQWm40RGI5bTRuUU5aNTBQOWVNUUFpekZTWk9pZGVrOUl3SURBUUFCbzBJd1FEQU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVmRmFKQktzeWpkeUkKbjhkRWlwbGlSZEp3Zll3d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFId3RqcENLUDZ5T21TUXdKT01XUGVxcApveFB1Y0JWNi9MT3FQam1Ga1AvMUtXRlNTWGtWMUMvSVZ1OEtzci9OTnRlSTcxamJWdEx2cVdIUEp0SFdWMTF4CjE4bk9nUWVGbnl3aXF2UXQrZVBRQ3BPeGpaMEJONThINXp0b0w2NzlTczBrdEdNWTEyN2p5S3ZURXEvbE1KWVEKKzFLRStMbDUzRTVCejBTQ04rQVNoYWcvNlBvT2svUU5VNUI0VCsrVlg3VGxscXlScTVGS2k0RXY0RkJpYlFKLwpldlJ6NGg5OEpLandjOU9wRnRkNUtiR001UUp6d1pzN2hGMFNHMjhMa2szOFVhclR1cThTNFl1SnBQOTU1L1VQCnNXR1UrclFRZEx6ZG1vYnk4Qjd0bWU1a04xc08yVTF3U0w5MkdBajU5Tk50aTk1YmtGQjVhUUR2cTgvV3FKND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
