apiVersion: {{ include "csi-driver-node.storageversion" . }}
kind: CSIDriver
metadata:
  name: {{ include "csi-driver-node.provisioner" . }}
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
