{{- if .Values.vpaEnabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: csi-driver-node
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: csi-driver
      minAllowed:
        cpu: {{ .Values.resources.driver.requests.cpu }}
        memory: {{ .Values.resources.driver.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.vpa.resourcePolicy.driver.maxAllowed.cpu }}
        memory: {{ .Values.vpa.resourcePolicy.driver.maxAllowed.memory }}
      controlledValues: RequestsOnly
    - containerName: csi-node-driver-registrar
      minAllowed:
        cpu: {{ .Values.resources.nodeDriverRegistrar.requests.cpu }}
        memory: {{ .Values.resources.nodeDriverRegistrar.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.vpa.resourcePolicy.nodeDriverRegistrar.maxAllowed.cpu }}
        memory: {{ .Values.vpa.resourcePolicy.nodeDriverRegistrar.maxAllowed.memory }}
      controlledValues: RequestsOnly
    - containerName: csi-liveness-probe
      minAllowed:
        cpu: {{ .Values.resources.livenessProbe.requests.cpu }}
        memory: {{ .Values.resources.livenessProbe.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.vpa.resourcePolicy.livenessProbe.maxAllowed.cpu }}
        memory: {{ .Values.vpa.resourcePolicy.livenessProbe.maxAllowed.memory }}
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: csi-driver-node
  updatePolicy:
    updateMode: "Auto"
{{- end }}
