---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: machine-controller-manager
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kubernetes
      role: machine-controller-manager
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
        {{- if .Values.useProjectedTokenMount }}
        # TODO(rfranzke): Remove in a future release.
        security.gardener.cloud/trigger: rollout
        {{- end }}
      labels:
        gardener.cloud/role: controlplane
        app: kubernetes
        role: machine-controller-manager
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-private-networks: allowed
        networking.gardener.cloud/to-seed-apiserver: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
        networking.gardener.cloud/from-prometheus: allowed
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: machine-controller-manager
      terminationGracePeriodSeconds: 5
      containers:
      - name: openstack-machine-controller-manager
        image: {{ index .Values.images "machine-controller-manager" }}
        imagePullPolicy: IfNotPresent
        command:
        - ./machine-controller-manager
        - --control-kubeconfig=inClusterConfig
        {{- if .Values.useTokenRequestor }}
        - --target-kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
        {{- else }}
        - --target-kubeconfig=/var/lib/machine-controller-manager/kubeconfig
        {{- end }}
        - --namespace={{ .Release.Namespace }}
        - --port={{ .Values.metricsPort }}
        - --machine-safety-apiserver-statuscheck-timeout=30s
        - --machine-safety-apiserver-statuscheck-period=1m
        - --machine-safety-orphan-vms-period=30m
        - --machine-safety-overshooting-period=1m
        - --safety-up=2
        - --safety-down=1
        - --delete-migrated-machine-class=true
        - --v=3
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: {{ .Values.metricsPort }}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - name: metrics
          containerPort: {{ .Values.metricsPort }}
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 350m
            memory: 256Mi
        volumeMounts:
        {{- if .Values.useTokenRequestor }}
        - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
          name: kubeconfig
          readOnly: true
        {{- else }}
        - mountPath: /var/lib/machine-controller-manager
          name: machine-controller-manager
          readOnly: true
        {{- end }}
      - name: provider-openstack
        image: {{ index .Values.images "machine-controller-manager-provider-openstack" }}
        imagePullPolicy: IfNotPresent
        command:
        - ./machine-controller
        - --control-kubeconfig=inClusterConfig
        - --namespace={{ .Release.Namespace }}
        - --port={{ .Values.metricsPortOpenstack}}
        {{- if .Values.useTokenRequestor }}
        - --target-kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
        {{- else }}
        - --target-kubeconfig=/var/lib/machine-controller-manager/kubeconfig
        {{- end }}
        - --v=3
        - --machine-creation-timeout=20m
        - --machine-drain-timeout=2h
        - --machine-health-timeout=10m
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: {{ .Values.metricsPortOpenstack }}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        {{- if .Values.useTokenRequestor }}
        - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
          name: kubeconfig
          readOnly: true
        {{- else }}
        - mountPath: /var/lib/machine-controller-manager
          name: machine-controller-manager
          readOnly: true
        {{- end }}
      volumes:
      {{- if .Values.useTokenRequestor }}
      - name: kubeconfig
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
                - key: kubeconfig
                  path: kubeconfig
              name: generic-token-kubeconfig
              optional: false
          - secret:
              items:
                - key: token
                  path: token
              name: shoot-access-machine-controller-manager
              optional: false
      {{- else }}
      - name: machine-controller-manager
        secret:
          secretName: machine-controller-manager
      {{- end }}
