---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: machine-controller-manager
    high-availability-config.resources.gardener.cloud/type: controller
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kubernetes
      role: machine-controller-manager
  template:
    metadata:
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        gardener.cloud/role: controlplane
        app: kubernetes
        role: machine-controller-manager
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-private-networks: allowed
        networking.gardener.cloud/to-seed-apiserver: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
        networking.gardener.cloud/from-prometheus: allowed
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: machine-controller-manager
      priorityClassName: gardener-system-300
      terminationGracePeriodSeconds: 5
      containers:
      - name: openstack-machine-controller-manager
        image: {{ index .Values.images "machine-controller-manager" }}
        imagePullPolicy: IfNotPresent
        command:
        - ./machine-controller-manager
        - --control-kubeconfig=inClusterConfig
        - --target-kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
        - --namespace={{ .Release.Namespace }}
        - --port={{ .Values.metricsPort }}
        - --machine-safety-apiserver-statuscheck-timeout=30s
        - --machine-safety-apiserver-statuscheck-period=1m
        - --machine-safety-orphan-vms-period=30m
        - --machine-safety-overshooting-period=1m
        - --safety-up=2
        - --safety-down=1
        - --delete-migrated-machine-class=true
        - --v=3
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: {{ .Values.metricsPort }}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - name: metrics
          containerPort: {{ .Values.metricsPort }}
          protocol: TCP
        resources:
{{ toYaml .Values.resources.mcm | indent 10 }}
        volumeMounts:
        - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
          name: kubeconfig
          readOnly: true
      - name: provider-openstack
        image: {{ index .Values.images "machine-controller-manager-provider-openstack" }}
        imagePullPolicy: IfNotPresent
        command:
        - ./machine-controller
        - --control-kubeconfig=inClusterConfig
        - --namespace={{ .Release.Namespace }}
        - --port={{ .Values.metricsPortOpenstack}}
        - --target-kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
        - --v=3
        - --machine-creation-timeout=20m
        - --machine-drain-timeout=2h
        - --machine-health-timeout=10m
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: {{ .Values.metricsPortOpenstack }}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources.mcmProviderOpenstack | indent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
          name: kubeconfig
          readOnly: true
      volumes:
      - name: kubeconfig
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: kubeconfig
                path: kubeconfig
              name: {{ .Values.genericTokenKubeconfigSecretName }}
              optional: false
          - secret:
              items:
              - key: token
                path: token
              name: shoot-access-machine-controller-manager
              optional: false
