{{- if semverCompare ">= 1.21-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: machine-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: machine-controller-manager
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: kubernetes
      role: machine-controller-manager
