apiVersion: v1
kind: ServiceAccount
metadata:
  name: machine-controller-manager
  namespace: {{ .Release.Namespace }}
{{- if .Values.useProjectedTokenMount }}
automountServiceAccountToken: false
{{- end }}
