apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
  name: cloud-controller-manager-openstack-cloud-controller-manager
spec:
  filters:
  - parser:
      keyName: log
      parser: kube-apiserver-parser
      reserveData: true
  match: kubernetes.*cloud-controller-manager*openstack-cloud-controller-manager*
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
  name: machine-controller-manager-openstack
spec:
  filters:
  - parser:
      keyName: log
      parser: kube-apiserver-parser
      reserveData: true
  match: kubernetes.*machine-controller-manager*openstack*
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
  name: csi-driver-controller-openstack-csi
spec:
  filters:
  - parser:
      keyName: log
      parser: kube-apiserver-parser
      reserveData: true
  match: kubernetes.*csi-driver-controller*openstack-csi*
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
  name: csi-snapshot-openstack-csi
spec:
  filters:
  - parser:
      keyName: log
      parser: kube-apiserver-parser
      reserveData: true
  match: kubernetes.*csi-snapshot*openstack-csi*
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
  name: modify-provider-openstack
spec:
  filters:
  - modify:
      conditions:
        - keyValueMatches:
            tag: ^kubernetes\.var\.log\.containers\.(cloud-controller-manager-.+?_.+?_openstack-cloud-controller-manager|csi-driver-controller-.+?_.+?_openstack-csi)
      rules:
        - add:
            __gardener_multitenant_id__: operator;user
  - modify:
      conditions:
        - keyValueMatches:
            tag: ^kubernetes\.var\.log\.containers\.machine-controller-manager-.+?_.+?_(openstack-machine-controller-manager|provider-openstack)
      rules:
        - add:
            __gardener_multitenant_id__: operator;user
  match:  kubernetes.*
