{{- if gt (int .Values.replicaCount) 1 }}
{{- if semverCompare ">= 1.21-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  maxUnavailable: {{ sub (int .Values.replicaCount) 1 }}
  selector:
    matchLabels:
{{ include "labels" . | indent 6 }}
{{- end }}
