apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
{{- if ne .Values.gardener.version "" }}
{{- if semverCompare ">= 1.37-0" .Values.gardener.version }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
