{{- if .Values.vpa.enabled}}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "name" . }}-vpa
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: gardener-extension-provider-openstack
        controlledValues: RequestsOnly
        controlledResources: ["memory", "cpu"]
      - containerName: '*'
        mode: "Off"
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "name" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode }}
{{- end }}
