images:
  csi-driver-nfs: image-repository:image-tag
  csi-node-driver-registrar: image-repository:image-tag
  csi-liveness-probe: image-repository:image-tag
  csi-provisioner: image-repository:image-tag

driver:
  mountPermissions: 0777

pspDisabled: false
vpaEnabled: false
dnsPolicy: ClusterFirstWithHostNet # available values: Default, ClusterFirstWithHostNet, ClusterFirst

resources:
  driverNode:
    requests:
      cpu: 15m
      memory: 42Mi
    limits:
      memory: 2Gi
  nodeDriverRegistrar:
    requests:
      cpu: 11m
      memory: 32Mi
    limits:
      memory: 1Gi
  livenessProbe:
    requests:
      cpu: 11m
      memory: 32Mi
    limits:
      memory: 200Mi
  provisioner:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      memory: 400Mi
  driverController:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      memory: 200Mi

feature:
  enableFSGroupPolicy: true
  enableInlineVolume: false

controller:
  podAnnotations: {}
  replicas: 1
  workingMountDir: "/tmp"
  livenessProbe:
    healthPort: 29652

node:
  livenessProbe:
    healthPort: 26147

vpa:
  resourcePolicy:
    driverController:
      maxAllowed:
        cpu: 800m
        memory: 2G
    provisioner:
      maxAllowed:
        cpu: 800m
        memory: 4G
    livenessProbe:
      maxAllowed:
        cpu: 500m
        memory: 2G