//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (c) SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	healthcheckconfig "github.com/gardener/gardener/extensions/pkg/controller/healthcheck/config"
	runtime "k8s.io/apimachinery/pkg/runtime"
	componentbaseconfig "k8s.io/component-base/config"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSI) DeepCopyInto(out *CSI) {
	*out = *in
	if in.CSIAttacher != nil {
		in, out := &in.CSIAttacher, &out.CSIAttacher
		*out = new(CSIAttacher)
		(*in).DeepCopyInto(*out)
	}
	if in.CSIDriverCinder != nil {
		in, out := &in.CSIDriverCinder, &out.CSIDriverCinder
		*out = new(CSIDriverCinder)
		(*in).DeepCopyInto(*out)
	}
	if in.CSIProvisioner != nil {
		in, out := &in.CSIProvisioner, &out.CSIProvisioner
		*out = new(CSIProvisioner)
		(*in).DeepCopyInto(*out)
	}
	if in.CSIResizer != nil {
		in, out := &in.CSIResizer, &out.CSIResizer
		*out = new(CSIResizer)
		(*in).DeepCopyInto(*out)
	}
	if in.CSISnapshotController != nil {
		in, out := &in.CSISnapshotController, &out.CSISnapshotController
		*out = new(CSISnapshotController)
		(*in).DeepCopyInto(*out)
	}
	if in.CSISnapshotter != nil {
		in, out := &in.CSISnapshotter, &out.CSISnapshotter
		*out = new(CSISnapshotter)
		(*in).DeepCopyInto(*out)
	}
	if in.CSILivenessProbe != nil {
		in, out := &in.CSILivenessProbe, &out.CSILivenessProbe
		*out = new(CSILivenessProbe)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSI.
func (in *CSI) DeepCopy() *CSI {
	if in == nil {
		return nil
	}
	out := new(CSI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIAttacher) DeepCopyInto(out *CSIAttacher) {
	*out = *in
	if in.RetryIntervalStart != nil {
		in, out := &in.RetryIntervalStart, &out.RetryIntervalStart
		*out = new(string)
		**out = **in
	}
	if in.RetryIntervalMax != nil {
		in, out := &in.RetryIntervalMax, &out.RetryIntervalMax
		*out = new(string)
		**out = **in
	}
	if in.ReconcileSync != nil {
		in, out := &in.ReconcileSync, &out.ReconcileSync
		*out = new(string)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.Verbose != nil {
		in, out := &in.Verbose, &out.Verbose
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIAttacher.
func (in *CSIAttacher) DeepCopy() *CSIAttacher {
	if in == nil {
		return nil
	}
	out := new(CSIAttacher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIDriverCinder) DeepCopyInto(out *CSIDriverCinder) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.Verbose != nil {
		in, out := &in.Verbose, &out.Verbose
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIDriverCinder.
func (in *CSIDriverCinder) DeepCopy() *CSIDriverCinder {
	if in == nil {
		return nil
	}
	out := new(CSIDriverCinder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSILivenessProbe) DeepCopyInto(out *CSILivenessProbe) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.Verbose != nil {
		in, out := &in.Verbose, &out.Verbose
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSILivenessProbe.
func (in *CSILivenessProbe) DeepCopy() *CSILivenessProbe {
	if in == nil {
		return nil
	}
	out := new(CSILivenessProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIProvisioner) DeepCopyInto(out *CSIProvisioner) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.Verbose != nil {
		in, out := &in.Verbose, &out.Verbose
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIProvisioner.
func (in *CSIProvisioner) DeepCopy() *CSIProvisioner {
	if in == nil {
		return nil
	}
	out := new(CSIProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIResizer) DeepCopyInto(out *CSIResizer) {
	*out = *in
	if in.CSITimeout != nil {
		in, out := &in.CSITimeout, &out.CSITimeout
		*out = new(string)
		**out = **in
	}
	if in.Verbose != nil {
		in, out := &in.Verbose, &out.Verbose
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIResizer.
func (in *CSIResizer) DeepCopy() *CSIResizer {
	if in == nil {
		return nil
	}
	out := new(CSIResizer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSISnapshotController) DeepCopyInto(out *CSISnapshotController) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.Verbose != nil {
		in, out := &in.Verbose, &out.Verbose
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSISnapshotController.
func (in *CSISnapshotController) DeepCopy() *CSISnapshotController {
	if in == nil {
		return nil
	}
	out := new(CSISnapshotController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSISnapshotter) DeepCopyInto(out *CSISnapshotter) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.Verbose != nil {
		in, out := &in.Verbose, &out.Verbose
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSISnapshotter.
func (in *CSISnapshotter) DeepCopy() *CSISnapshotter {
	if in == nil {
		return nil
	}
	out := new(CSISnapshotter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfiguration) DeepCopyInto(out *ControllerConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.ClientConnection != nil {
		in, out := &in.ClientConnection, &out.ClientConnection
		*out = new(componentbaseconfig.ClientConnectionConfiguration)
		**out = **in
	}
	in.ETCD.DeepCopyInto(&out.ETCD)
	if in.HealthCheckConfig != nil {
		in, out := &in.HealthCheckConfig, &out.HealthCheckConfig
		*out = new(healthcheckconfig.HealthCheckConfig)
		**out = **in
	}
	if in.CSI != nil {
		in, out := &in.CSI, &out.CSI
		*out = new(CSI)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfiguration.
func (in *ControllerConfiguration) DeepCopy() *ControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ETCD) DeepCopyInto(out *ETCD) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	in.Backup.DeepCopyInto(&out.Backup)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ETCD.
func (in *ETCD) DeepCopy() *ETCD {
	if in == nil {
		return nil
	}
	out := new(ETCD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ETCDBackup) DeepCopyInto(out *ETCDBackup) {
	*out = *in
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ETCDBackup.
func (in *ETCDBackup) DeepCopy() *ETCDBackup {
	if in == nil {
		return nil
	}
	out := new(ETCDBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ETCDStorage) DeepCopyInto(out *ETCDStorage) {
	*out = *in
	if in.ClassName != nil {
		in, out := &in.ClassName, &out.ClassName
		*out = new(string)
		**out = **in
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		x := (*in).DeepCopy()
		*out = &x
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ETCDStorage.
func (in *ETCDStorage) DeepCopy() *ETCDStorage {
	if in == nil {
		return nil
	}
	out := new(ETCDStorage)
	in.DeepCopyInto(out)
	return out
}
