// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gardener/gardener-extension-provider-openstack/pkg/controller/infrastructure/infraflow/access (interfaces: NetworkingAccess)
//
// Generated by this command:
//
//	mockgen -destination=pkg/controller/infrastructure/infraflow/access/mocks/access_mocks.go -package=mocks github.com/gardener/gardener-extension-provider-openstack/pkg/controller/infrastructure/infraflow/access NetworkingAccess
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	access "github.com/gardener/gardener-extension-provider-openstack/pkg/controller/infrastructure/infraflow/access"
	groups "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/security/groups"
	rules "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/security/rules"
	subnets "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/subnets"
	gomock "go.uber.org/mock/gomock"
)

// MockNetworkingAccess is a mock of NetworkingAccess interface.
type MockNetworkingAccess struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkingAccessMockRecorder
	isgomock struct{}
}

// MockNetworkingAccessMockRecorder is the mock recorder for MockNetworkingAccess.
type MockNetworkingAccessMockRecorder struct {
	mock *MockNetworkingAccess
}

// NewMockNetworkingAccess creates a new mock instance.
func NewMockNetworkingAccess(ctrl *gomock.Controller) *MockNetworkingAccess {
	mock := &MockNetworkingAccess{ctrl: ctrl}
	mock.recorder = &MockNetworkingAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkingAccess) EXPECT() *MockNetworkingAccessMockRecorder {
	return m.recorder
}

// AddRouterInterfaceAndWait mocks base method.
func (m *MockNetworkingAccess) AddRouterInterfaceAndWait(ctx context.Context, routerID, subnetID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRouterInterfaceAndWait", ctx, routerID, subnetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRouterInterfaceAndWait indicates an expected call of AddRouterInterfaceAndWait.
func (mr *MockNetworkingAccessMockRecorder) AddRouterInterfaceAndWait(ctx, routerID, subnetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRouterInterfaceAndWait", reflect.TypeOf((*MockNetworkingAccess)(nil).AddRouterInterfaceAndWait), ctx, routerID, subnetID)
}

// CreateNetwork mocks base method.
func (m *MockNetworkingAccess) CreateNetwork(ctx context.Context, desired *access.Network) (*access.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", ctx, desired)
	ret0, _ := ret[0].(*access.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockNetworkingAccessMockRecorder) CreateNetwork(ctx, desired any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockNetworkingAccess)(nil).CreateNetwork), ctx, desired)
}

// CreateRouter mocks base method.
func (m *MockNetworkingAccess) CreateRouter(ctx context.Context, desired *access.Router) (*access.Router, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRouter", ctx, desired)
	ret0, _ := ret[0].(*access.Router)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRouter indicates an expected call of CreateRouter.
func (mr *MockNetworkingAccessMockRecorder) CreateRouter(ctx, desired any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRouter", reflect.TypeOf((*MockNetworkingAccess)(nil).CreateRouter), ctx, desired)
}

// CreateSecurityGroup mocks base method.
func (m *MockNetworkingAccess) CreateSecurityGroup(ctx context.Context, desired *groups.SecGroup) (*groups.SecGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecurityGroup", ctx, desired)
	ret0, _ := ret[0].(*groups.SecGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecurityGroup indicates an expected call of CreateSecurityGroup.
func (mr *MockNetworkingAccessMockRecorder) CreateSecurityGroup(ctx, desired any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecurityGroup", reflect.TypeOf((*MockNetworkingAccess)(nil).CreateSecurityGroup), ctx, desired)
}

// CreateSubnet mocks base method.
func (m *MockNetworkingAccess) CreateSubnet(ctx context.Context, desired *subnets.Subnet, prefixlen *int) (*subnets.Subnet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubnet", ctx, desired, prefixlen)
	ret0, _ := ret[0].(*subnets.Subnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubnet indicates an expected call of CreateSubnet.
func (mr *MockNetworkingAccessMockRecorder) CreateSubnet(ctx, desired, prefixlen any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubnet", reflect.TypeOf((*MockNetworkingAccess)(nil).CreateSubnet), ctx, desired, prefixlen)
}

// GetNetworkByID mocks base method.
func (m *MockNetworkingAccess) GetNetworkByID(ctx context.Context, id string) (*access.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkByID", ctx, id)
	ret0, _ := ret[0].(*access.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkByID indicates an expected call of GetNetworkByID.
func (mr *MockNetworkingAccessMockRecorder) GetNetworkByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkByID", reflect.TypeOf((*MockNetworkingAccess)(nil).GetNetworkByID), ctx, id)
}

// GetNetworkByName mocks base method.
func (m *MockNetworkingAccess) GetNetworkByName(ctx context.Context, name string) ([]*access.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkByName", ctx, name)
	ret0, _ := ret[0].([]*access.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkByName indicates an expected call of GetNetworkByName.
func (mr *MockNetworkingAccessMockRecorder) GetNetworkByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkByName", reflect.TypeOf((*MockNetworkingAccess)(nil).GetNetworkByName), ctx, name)
}

// GetRouterByID mocks base method.
func (m *MockNetworkingAccess) GetRouterByID(ctx context.Context, id string) (*access.Router, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouterByID", ctx, id)
	ret0, _ := ret[0].(*access.Router)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRouterByID indicates an expected call of GetRouterByID.
func (mr *MockNetworkingAccessMockRecorder) GetRouterByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouterByID", reflect.TypeOf((*MockNetworkingAccess)(nil).GetRouterByID), ctx, id)
}

// GetRouterByName mocks base method.
func (m *MockNetworkingAccess) GetRouterByName(ctx context.Context, name string) ([]*access.Router, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouterByName", ctx, name)
	ret0, _ := ret[0].([]*access.Router)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRouterByName indicates an expected call of GetRouterByName.
func (mr *MockNetworkingAccessMockRecorder) GetRouterByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouterByName", reflect.TypeOf((*MockNetworkingAccess)(nil).GetRouterByName), ctx, name)
}

// GetRouterInterfacePortID mocks base method.
func (m *MockNetworkingAccess) GetRouterInterfacePortID(ctx context.Context, routerID, subnetID string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouterInterfacePortID", ctx, routerID, subnetID)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRouterInterfacePortID indicates an expected call of GetRouterInterfacePortID.
func (mr *MockNetworkingAccessMockRecorder) GetRouterInterfacePortID(ctx, routerID, subnetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouterInterfacePortID", reflect.TypeOf((*MockNetworkingAccess)(nil).GetRouterInterfacePortID), ctx, routerID, subnetID)
}

// GetSecurityGroupByID mocks base method.
func (m *MockNetworkingAccess) GetSecurityGroupByID(ctx context.Context, id string) (*groups.SecGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityGroupByID", ctx, id)
	ret0, _ := ret[0].(*groups.SecGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityGroupByID indicates an expected call of GetSecurityGroupByID.
func (mr *MockNetworkingAccessMockRecorder) GetSecurityGroupByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityGroupByID", reflect.TypeOf((*MockNetworkingAccess)(nil).GetSecurityGroupByID), ctx, id)
}

// GetSecurityGroupByName mocks base method.
func (m *MockNetworkingAccess) GetSecurityGroupByName(ctx context.Context, name string) ([]*groups.SecGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityGroupByName", ctx, name)
	ret0, _ := ret[0].([]*groups.SecGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityGroupByName indicates an expected call of GetSecurityGroupByName.
func (mr *MockNetworkingAccessMockRecorder) GetSecurityGroupByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityGroupByName", reflect.TypeOf((*MockNetworkingAccess)(nil).GetSecurityGroupByName), ctx, name)
}

// GetSubnetByID mocks base method.
func (m *MockNetworkingAccess) GetSubnetByID(ctx context.Context, id string) (*subnets.Subnet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetByID", ctx, id)
	ret0, _ := ret[0].(*subnets.Subnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetByID indicates an expected call of GetSubnetByID.
func (mr *MockNetworkingAccessMockRecorder) GetSubnetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetByID", reflect.TypeOf((*MockNetworkingAccess)(nil).GetSubnetByID), ctx, id)
}

// GetSubnetByName mocks base method.
func (m *MockNetworkingAccess) GetSubnetByName(ctx context.Context, networkID, name string) ([]*subnets.Subnet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetByName", ctx, networkID, name)
	ret0, _ := ret[0].([]*subnets.Subnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetByName indicates an expected call of GetSubnetByName.
func (mr *MockNetworkingAccessMockRecorder) GetSubnetByName(ctx, networkID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetByName", reflect.TypeOf((*MockNetworkingAccess)(nil).GetSubnetByName), ctx, networkID, name)
}

// LookupFloatingPoolSubnetIDs mocks base method.
func (m *MockNetworkingAccess) LookupFloatingPoolSubnetIDs(ctx context.Context, networkID, floatingPoolSubnetNameRegex string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupFloatingPoolSubnetIDs", ctx, networkID, floatingPoolSubnetNameRegex)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupFloatingPoolSubnetIDs indicates an expected call of LookupFloatingPoolSubnetIDs.
func (mr *MockNetworkingAccessMockRecorder) LookupFloatingPoolSubnetIDs(ctx, networkID, floatingPoolSubnetNameRegex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupFloatingPoolSubnetIDs", reflect.TypeOf((*MockNetworkingAccess)(nil).LookupFloatingPoolSubnetIDs), ctx, networkID, floatingPoolSubnetNameRegex)
}

// RemoveRouterInterfaceAndWait mocks base method.
func (m *MockNetworkingAccess) RemoveRouterInterfaceAndWait(ctx context.Context, routerID, subnetID, portID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRouterInterfaceAndWait", ctx, routerID, subnetID, portID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRouterInterfaceAndWait indicates an expected call of RemoveRouterInterfaceAndWait.
func (mr *MockNetworkingAccessMockRecorder) RemoveRouterInterfaceAndWait(ctx, routerID, subnetID, portID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRouterInterfaceAndWait", reflect.TypeOf((*MockNetworkingAccess)(nil).RemoveRouterInterfaceAndWait), ctx, routerID, subnetID, portID)
}

// UpdateNetwork mocks base method.
func (m *MockNetworkingAccess) UpdateNetwork(ctx context.Context, desired, current *access.Network) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNetwork", ctx, desired, current)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNetwork indicates an expected call of UpdateNetwork.
func (mr *MockNetworkingAccessMockRecorder) UpdateNetwork(ctx, desired, current any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNetwork", reflect.TypeOf((*MockNetworkingAccess)(nil).UpdateNetwork), ctx, desired, current)
}

// UpdateRouter mocks base method.
func (m *MockNetworkingAccess) UpdateRouter(ctx context.Context, desired, current *access.Router) (bool, *access.Router, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRouter", ctx, desired, current)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*access.Router)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateRouter indicates an expected call of UpdateRouter.
func (mr *MockNetworkingAccessMockRecorder) UpdateRouter(ctx, desired, current any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRouter", reflect.TypeOf((*MockNetworkingAccess)(nil).UpdateRouter), ctx, desired, current)
}

// UpdateSecurityGroupRules mocks base method.
func (m *MockNetworkingAccess) UpdateSecurityGroupRules(ctx context.Context, group *groups.SecGroup, desiredRules []rules.SecGroupRule, allowDelete func(*rules.SecGroupRule) bool) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecurityGroupRules", ctx, group, desiredRules, allowDelete)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSecurityGroupRules indicates an expected call of UpdateSecurityGroupRules.
func (mr *MockNetworkingAccessMockRecorder) UpdateSecurityGroupRules(ctx, group, desiredRules, allowDelete any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecurityGroupRules", reflect.TypeOf((*MockNetworkingAccess)(nil).UpdateSecurityGroupRules), ctx, group, desiredRules, allowDelete)
}

// UpdateSubnet mocks base method.
func (m *MockNetworkingAccess) UpdateSubnet(ctx context.Context, desired, current *subnets.Subnet) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubnet", ctx, desired, current)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubnet indicates an expected call of UpdateSubnet.
func (mr *MockNetworkingAccessMockRecorder) UpdateSubnet(ctx, desired, current any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubnet", reflect.TypeOf((*MockNetworkingAccess)(nil).UpdateSubnet), ctx, desired, current)
}
