apiVersion: testmachinery.sapcloud.io/v1beta1
kind: Testrun
metadata:
  generateName: tm-extension-openstack-
  namespace: default
spec:
  ttlSecondsAfterFinished: 172800 # 2 days
  {{- if .Values.revision }}
  locationSets:
    - default: true
      name: provider-openstack
      locations:
        - type: git
          repo: https://github.com/gardener/gardener-extension-provider-openstack.git
          revision: {{ .Values.revision }}
  {{- end }}

  config:
    - name: DOMAIN_NAME
      type: env
      valueFrom:
        secretKeyRef:
          name: shoot-operator-ccee-cp-eu-de-1
          key: domainName
    - name: TENANT_NAME
      type: env
      valueFrom:
        secretKeyRef:
          name: shoot-operator-ccee-cp-eu-de-1
          key: tenantName
    - name: AUTH_URL
      type: env
      valueFrom:
        secretKeyRef:
          name: shoot-operator-ccee-cp-eu-de-1
          key: authURL
    - name: FLOATING_POOL_NAME
      type: env
      valueFrom:
        secretKeyRef:
          name: shoot-operator-ccee-cp-eu-de-1
          key: floatingPoolName
    - name: APPLICATION_CREDENTIAL_ID
      type: env
      valueFrom:
        secretKeyRef:
          name: shoot-operator-ccee-cp-eu-de-1
          key: applicationCredentialID
    - name: APPLICATION_CREDENTIAL_NAME
      type: env
      valueFrom:
        secretKeyRef:
          name: shoot-operator-ccee-cp-eu-de-1
          key: applicationCredentialName
    - name: APPLICATION_CREDENTIAL_SECRET
      type: env
      valueFrom:
        secretKeyRef:
          name: shoot-operator-ccee-cp-eu-de-1
          key: applicationCredentialSecret
    - name: FLOATING_POOL_NAME
      type: env
      valueFrom:
        secretKeyRef:
          name: shoot-operator-ccee-cp-eu-de-1
          key: floatingPoolName
    - name: REGION
      type: env
      value: eu-de-1
    - name: USER_NAME_BACKUP
      type: env
      valueFrom:
        secretKeyRef:
          name: backup-operator-ccee-cp-eu-de-1
          key: username
    - name: PASSWORD_BACKUP
      type: env
      valueFrom:
        secretKeyRef:
          name: backup-operator-ccee-cp-eu-de-1
          key: password

  testflow:
    - name: infrastructure-test
      definition:
        name: infrastructure-test
    - name: backupbucket-test
      definition:
        name: backupbucket-test
        config:
          - name: LOG_LEVEL
            type: env
            value: debug
          - name: USE_EXISTING_CLUSTER
            type: env
            value: "true"
    - name: bastion-test
      definition:
        name: bastion-test
    - name: dnsrecord-test
      definition:
        name: dnsrecord-test
