{
 "title": "Cloud Controller Manager",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cloud-controller-manager Memory Usage",
   "type": "graph",
   "description": "Shows the memory usage of the cloud-controller-manager.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"cloud-controller-manager-(.+)\"}",
     "legendFormat": "current"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"cloud-controller-manager-(.+)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"cloud-controller-manager-(.+)\"}",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Cloud-controller-manager CPU usage",
   "type": "graph",
   "description": "Shows the CPU usage of the cloud-controller-manager and shows the requests and limits.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"cloud-controller-manager-(.+)\"}[5m])",
     "legendFormat": "current"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"cloud-controller-manager-(.+)\"}",
     "legendFormat": "limits"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"cloud-controller-manager-(.+)\"}",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Request Rate to Kube API",
   "type": "graph",
   "description": "The average http request rate of the last 5m executed by the Cloud Controller Manager to the cluster API server. The request are split by their response status codes.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{host=~\".*kube-apiserver.*\", job=\"cloud-controller-manager\"}[5m])) by(code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Cloud Controller Managers UP",
   "type": "singlestat",
   "description": "Current uptime status of the cloud controller managers.",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"cloud-controller-manager\"} == 1) / sum(up{job=\"kube-controller-manager\"})) * 100"
    }
   ]
  }
 ]
}