---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: extensions.gardener.cloud:{{ .Values.providerName }}:machine-controller-manager
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extensions.gardener.cloud:{{ .Values.providerName }}:machine-controller-manager
subjects:
- kind: ServiceAccount
  name: machine-controller-manager
  namespace: kube-system
