name: Integration-Tests
description: |
  Runs Integration tests using TestMachinery

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  integrationtest:
    permissions:
      id-token: write
      contents: read
    uses: gardener/cc-utils/.github/workflows/run-testmachinery-tests.yaml@master
    with:
      test-command: |
        ${testrunner_run} \
         --no-execution-group \
         --testrun-prefix tm-extension-openstack- \
         --timeout=3600 \
         --testruns-chart-path=.ci/testruns/default \
         --set revision=$(git rev-parse @)

